server:
  port : 8000


spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/springapp
    username: postgres
    password: pass

  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

